## Here I provide some good to know features and examples for a quick warm up

<a id='toc'></a>
### Table of Contents

1. [The Zen of Python](#The-Zen-of-Python)
2. <a href='#kwd'>Keywords</a>
3. <a href='#caem'>Command and Edit Modes</a>
4. <a href='#smdex'>Some Markdown Examples</a>
5. <a href='#mfalt'>Math Formulae and using LaTex</a>
6. <a href='#bif'>Built-in Functions</a>
7. <a href='#strings'>Formatted Strings</a>
8. <a href='#shadeepcopy'>Shallow and Deep Copies</a>
9. <a href='#ladcomp'>List and Dict Comprehensions</a>
10. <a href='#numpy'>Numpy</a>
11. <a href='#arraydtypes'>Array Data Types</a>

### The Zen of Python

In [42]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


----
<a href='#toc'>Back to ToC</a>

<a id='kwd'></a>
### Keywords

In [44]:
help('keywords')


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



----
<a href='#toc'>Back to ToC</a>

<a id='caem'></a>
### Command and Edit Modes

- Enter : Edit Mode, makes the cursor active and goes in the selected cell.
    - Ctrl + Shift + minus : Splits the cell at cursor position  
    - Shift-Tab : Shows tooltip
- Esc : Command Mode, deactivates the cursor and text editing.
    - y : Change to Code
    - m : Change to Markdown
    - b : Insert new cell below
    - a : Insert new cell above
    - dd : Delete the cell
    - h : Keyboard shortcuts
    - Shift + m : Combines selected cells

In [2]:
print("Ctrl + Enter:", "Just runs the cell.")

Ctrl + Enter: Just runs the cell.


In [4]:
print("Alt + Enter:", "Runs the cell and insert a new cell below.")

Alt + Enter: Runs the cell and insert a new cell below.


In [7]:
print("Shift + Enter:", "Runs the cell and goes to the next cell below. If there is no cell below, then inserts a new cell.")

Shift + Enter: Runs the cell and goes to the next cell below. If there is no cell below, then inserts a new cell.


#### Specific Commands: Line and Cell Magics

- Line magic : %
- Cell magic : %%

In [1]:
print("We can see the available Line and Cell Magic commands as follows...")
magic_commands = %lsmagic

We can see the available Line and Cell Magic commands as follows...


In [3]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [36]:
# Let's see the type of this output.
type(magic_commands)

IPython.core.magics.basic.MagicsDisplay

In [37]:
# I will convert it to string type then using split() method I will create a list.
magic_split = str(magic_commands).split() #default delimiter is space!

# Now we can iterate over this list and print the magic commands
counter = 0
for item in magic_split:
    if item.startswith('%') and len(item) > 1:
        counter += 1
        print(str(counter).rjust(3), ": ", item)
    
print(f'There are {counter} magic commands.')

  1 :  %alias
  2 :  %alias_magic
  3 :  %autoawait
  4 :  %autocall
  5 :  %automagic
  6 :  %autosave
  7 :  %bookmark
  8 :  %cd
  9 :  %clear
 10 :  %cls
 11 :  %colors
 12 :  %conda
 13 :  %config
 14 :  %connect_info
 15 :  %copy
 16 :  %ddir
 17 :  %debug
 18 :  %dhist
 19 :  %dirs
 20 :  %doctest_mode
 21 :  %echo
 22 :  %ed
 23 :  %edit
 24 :  %env
 25 :  %gui
 26 :  %hist
 27 :  %history
 28 :  %killbgscripts
 29 :  %ldir
 30 :  %less
 31 :  %load
 32 :  %load_ext
 33 :  %loadpy
 34 :  %logoff
 35 :  %logon
 36 :  %logstart
 37 :  %logstate
 38 :  %logstop
 39 :  %ls
 40 :  %lsmagic
 41 :  %macro
 42 :  %magic
 43 :  %matplotlib
 44 :  %mkdir
 45 :  %more
 46 :  %notebook
 47 :  %page
 48 :  %pastebin
 49 :  %pdb
 50 :  %pdef
 51 :  %pdoc
 52 :  %pfile
 53 :  %pinfo
 54 :  %pinfo2
 55 :  %pip
 56 :  %popd
 57 :  %pprint
 58 :  %precision
 59 :  %prun
 60 :  %psearch
 61 :  %psource
 62 :  %pushd
 63 :  %pwd
 64 :  %pycat
 65 :  %pylab
 66 :  %qtconsole
 67 :  %quickref
 68 : 

In [25]:
# So, now we have learned that there are 121 magic commands and 93 of these is line magic commands and the remaining 28 
# command is cell magic commands.

In [35]:
# We can add ? to the end of a magic command to get some help about it.
# or we can use shift + tab as well
%%timeit?

----
<a href='#toc'>Back to ToC</a>

<a id='smdex'></a>
### Some Markdown Examples

#### Table of Contents

1. [Title 1](#Title-1)  

2. [Title 2](#Title-2)

1. [Title 3](#Title-3)  
    1. [Subtitle 1](#Subtitle-1)  
    1. [Subtitle 2](#Subtitle-2)  

-----
[Back to TOC](#Table-of-Contents)

## Title 1



-----
[Back to TOC](#Table-of-Contents)

## Title 2

-----
[Back to TOC](#Table-of-Contents)

## Title 3

-----
[Back to TOC](#Table-of-Contents)

#### Subtitle-1

-----
[Back to TOC](#Table-of-Contents)

#### Subtitle-2

<a id='mfalt'></a>
### Math Formulae and using LaTex

In [41]:
# Some examples

alpha: $\alpha$

beta: $\beta$

 theta : $\theta$

$\int_0^{\pi} \sin(\theta)\ d\theta = 2$

The formula to calculate Body Mass Index (BMI) (assuming weight in pounds and height in inches) 

$BMI = \large{\frac{weight \times 703}{height^2}}$

-----
[Back to TOC](#Table-of-Contents)

<a id='bif'></a>
### Built-in Functions (with embedded HTML)

In [46]:
from IPython.display import IFrame

IFrame(src='https://docs.python.org/3/library/functions.html#built-in-functions', width=1000, height=600)

----
<a href='#toc'>Back to ToC</a>

<a id='strings'></a>
### Formatted Strings

In [53]:
# Leading (prepending) zeros
num1 = 5
print(f'This is a number with leading zeros. => "{num1:07}"')

This is a number with leading zeros. => "0000005"


In [52]:
print(f'This is a number with leading spaces. => "{num1:7}"')

This is a number with leading spaces. => "      5"


In [63]:
num2 = 123.12999999
print(f'This is a number with leading zeros and three digit decimal. => "{num2:09.3f}"')

This is a number with leading zeros and three digit decimal. => "00123.130"


In [65]:
num2 = 123.12999999
print(f'This is a number with leading spaces and three digit decimal. => "{num2:9.3f}"')

This is a number with leading spaces and three digit decimal. => "  123.130"


----
<a href='#toc'>Back to ToC</a>

<a id='shadeepcopy'></a>
### Shallow and Deep Copies

In [71]:
original = ["a", "b", "c", "d"]

# deep copy 1
deep_copy1 = original[:]

# deep copy 2
deep_copy2 = original.copy()

# shallow copy
shallow_copy = original


In [72]:
# Now we will change the copies and then check if the original list has changed or not.
# First attempt
deep_copy1[:] = "dc1"

In [77]:
print("Deep Copy 1: ", deep_copy1)
print("Original:", original)

Deep Copy 1:  ['d', 'c', '1']
Original: ['a', 'b', 'c', 'd']


In [76]:
# Second attempt
deep_copy2[:] = "dc2"

In [78]:
print("Deep Copy 2: ", deep_copy2)
print("Original:", original)

Deep Copy 2:  ['d', 'c', '2']
Original: ['a', 'b', 'c', 'd']


In [80]:
# Second attempt
shallow_copy[:] = "shallow"

In [81]:
print("Shallow Copy: ", shallow_copy)
print("Original:", original)

Shallow Copy:  ['s', 'h', 'a', 'l', 'l', 'o', 'w']
Original: ['s', 'h', 'a', 'l', 'l', 'o', 'w']


In [82]:
# As we can see above, the change in a shallow copy changes the original data! 

----
<a href='#toc'>Back to ToC</a>

<a id='ladcomp'></a>
### List and Dict Comprehensions

In [97]:
# List comprehension
list_comp = [num for num in range(10)]
list_comp

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [99]:
# Dict comprehension
dict_comp = {num: {num, num**2, num**3} for num in range(3, 7)}
dict_comp

{3: {3, 9, 27}, 4: {4, 16, 64}, 5: {5, 25, 125}, 6: {6, 36, 216}}

----
<a href='#toc'>Back to ToC</a>

<a id='numpy'></a>
### Numpy

In [1]:
import numpy as np

print(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

print("np.empty: ", np.empty(10))
print("np.zeros: ", np.zeros(10))
print()
print("np.ones: ", np.ones(10))
print("np.ones_like: ", np.ones_like(np.arange(10)))
print("np.empty_like: ", np.empty_like(np.arange(10)))
print("np.zeros_like: ", np.zeros_like(np.arange(10)))

[0 1 2 3 4 5 6 7 8 9]
np.empty:  [4.67296746e-307 1.69121096e-306 1.24611673e-306 6.23058028e-307
 8.45593934e-307 7.56593017e-307 1.20161390e-306 1.78021391e-306
 1.24611470e-306 0.00000000e+000]
np.zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

np.ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
np.ones_like:  [1 1 1 1 1 1 1 1 1 1]
np.empty_like:  [0 1 2 3 4 5 6 7 8 9]
np.zeros_like:  [0 0 0 0 0 0 0 0 0 0]


In [6]:
np.empty?

In [2]:
print(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

print("np.empty: ", np.empty(10))
print("np.zeros: ", np.zeros(10))
print()
print("np.ones: ", np.ones(10))
print("np.ones_like: ", np.ones_like(np.arange(10)))
print("np.empty_like: ", np.empty_like(np.arange(10)))
print("np.zeros_like: ", np.zeros_like(np.arange(10)))

[0 1 2 3 4 5 6 7 8 9]
np.empty:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
np.zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

np.ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
np.ones_like:  [1 1 1 1 1 1 1 1 1 1]
np.empty_like:  [0 1 2 3 4 5 6 7 8 9]
np.zeros_like:  [0 0 0 0 0 0 0 0 0 0]


In [41]:
print(np.arange(7))
print(np.arange(1, 7, 2))

[0 1 2 3 4 5 6]
[1 3 5]


In [53]:
print(np.linspace(0,12))  # Default 50 bins
print()
print('np.linspace uses default 50 bins')
print('with the last parameter we can change the bins size.')
print(np.linspace(0, 12, 4))

[ 0.          0.24489796  0.48979592  0.73469388  0.97959184  1.2244898
  1.46938776  1.71428571  1.95918367  2.20408163  2.44897959  2.69387755
  2.93877551  3.18367347  3.42857143  3.67346939  3.91836735  4.16326531
  4.40816327  4.65306122  4.89795918  5.14285714  5.3877551   5.63265306
  5.87755102  6.12244898  6.36734694  6.6122449   6.85714286  7.10204082
  7.34693878  7.59183673  7.83673469  8.08163265  8.32653061  8.57142857
  8.81632653  9.06122449  9.30612245  9.55102041  9.79591837 10.04081633
 10.28571429 10.53061224 10.7755102  11.02040816 11.26530612 11.51020408
 11.75510204 12.        ]

np.linspace uses default 50 bins
with the last parameter we can change the bins size.
[ 0.  4.  8. 12.]


----
<a href='#toc'>Back to ToC</a>

<a id='arraydtypes'></a>
### Array Data Types

In [63]:
# Array Data Types
for key, val in np.sctypeDict.items():
    print(f'{str(key).ljust(12)} : {val}')

?            : <class 'numpy.bool_'>
0            : <class 'numpy.bool_'>
byte         : <class 'numpy.int8'>
b            : <class 'numpy.int8'>
1            : <class 'numpy.int8'>
ubyte        : <class 'numpy.uint8'>
B            : <class 'numpy.uint8'>
2            : <class 'numpy.uint8'>
short        : <class 'numpy.int16'>
h            : <class 'numpy.int16'>
3            : <class 'numpy.int16'>
ushort       : <class 'numpy.uint16'>
H            : <class 'numpy.uint16'>
4            : <class 'numpy.uint16'>
i            : <class 'numpy.intc'>
5            : <class 'numpy.intc'>
uint         : <class 'numpy.uint32'>
I            : <class 'numpy.uintc'>
6            : <class 'numpy.uintc'>
intp         : <class 'numpy.int64'>
p            : <class 'numpy.int64'>
9            : <class 'numpy.int64'>
uintp        : <class 'numpy.uint64'>
P            : <class 'numpy.uint64'>
10           : <class 'numpy.uint64'>
long         : <class 'numpy.int32'>
l            : <class 'numpy.int32'>

----
<a href='#toc'>Back to ToC</a>