## Here I provide some good to know features and examples for a quick warm up

<a id='toc'></a>
### Table of Contents

1. [The Zen of Python](#The-Zen-of-Python)
2. <a href='#kwd'>Keywords</a>
3. <a href='#caem'>Command and Edit Modes</a>
4. <a href='#smdex'>Some Markdown Examples</a>
5. <a href='#mfalt'>Math Formulae and using LaTex</a>
6. <a href='#bif'>Built-in Functions</a>
7. <a href='#strings'>Formatted Strings</a>
8. <a href='#shadeepcopy'>Shallow and Deep Copies</a>
9. <a href='#ladcomp'>List and Dict Comprehensions</a>
10. <a href='#numpy'>Numpy</a>
11. <a href='#arraydtypes'>Array Data Types</a>
12. <a href='#pandas'>Pandas</a>
13. <a href='#readwrite'>Reading/Writing Files</a>

### The Zen of Python

In [42]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


----
<a href='#toc'>Back to ToC</a>

<a id='kwd'></a>
### Keywords

In [44]:
help('keywords')


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



----
<a href='#toc'>Back to ToC</a>

<a id='caem'></a>
### Command and Edit Modes

- Enter : Edit Mode, makes the cursor active and goes in the selected cell.
    - Ctrl + Shift + minus : Splits the cell at cursor position  
    - Shift-Tab : Shows tooltip
- Esc : Command Mode, deactivates the cursor and text editing.
    - y : Change to Code
    - m : Change to Markdown
    - b : Insert new cell below
    - a : Insert new cell above
    - dd : Delete the cell
    - h : Keyboard shortcuts
    - Shift + m : Combines selected cells

In [2]:
print("Ctrl + Enter:", "Just runs the cell.")

Ctrl + Enter: Just runs the cell.


In [4]:
print("Alt + Enter:", "Runs the cell and insert a new cell below.")

Alt + Enter: Runs the cell and insert a new cell below.


In [7]:
print("Shift + Enter:", "Runs the cell and goes to the next cell below. If there is no cell below, then inserts a new cell.")

Shift + Enter: Runs the cell and goes to the next cell below. If there is no cell below, then inserts a new cell.


#### Specific Commands: Line and Cell Magics

- Line magic : %
- Cell magic : %%

In [1]:
print("We can see the available Line and Cell Magic commands as follows...")
magic_commands = %lsmagic

We can see the available Line and Cell Magic commands as follows...


In [3]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [36]:
# Let's see the type of this output.
type(magic_commands)

IPython.core.magics.basic.MagicsDisplay

In [37]:
# I will convert it to string type then using split() method I will create a list.
magic_split = str(magic_commands).split() #default delimiter is space!

# Now we can iterate over this list and print the magic commands
counter = 0
for item in magic_split:
    if item.startswith('%') and len(item) > 1:
        counter += 1
        print(str(counter).rjust(3), ": ", item)
    
print(f'There are {counter} magic commands.')

  1 :  %alias
  2 :  %alias_magic
  3 :  %autoawait
  4 :  %autocall
  5 :  %automagic
  6 :  %autosave
  7 :  %bookmark
  8 :  %cd
  9 :  %clear
 10 :  %cls
 11 :  %colors
 12 :  %conda
 13 :  %config
 14 :  %connect_info
 15 :  %copy
 16 :  %ddir
 17 :  %debug
 18 :  %dhist
 19 :  %dirs
 20 :  %doctest_mode
 21 :  %echo
 22 :  %ed
 23 :  %edit
 24 :  %env
 25 :  %gui
 26 :  %hist
 27 :  %history
 28 :  %killbgscripts
 29 :  %ldir
 30 :  %less
 31 :  %load
 32 :  %load_ext
 33 :  %loadpy
 34 :  %logoff
 35 :  %logon
 36 :  %logstart
 37 :  %logstate
 38 :  %logstop
 39 :  %ls
 40 :  %lsmagic
 41 :  %macro
 42 :  %magic
 43 :  %matplotlib
 44 :  %mkdir
 45 :  %more
 46 :  %notebook
 47 :  %page
 48 :  %pastebin
 49 :  %pdb
 50 :  %pdef
 51 :  %pdoc
 52 :  %pfile
 53 :  %pinfo
 54 :  %pinfo2
 55 :  %pip
 56 :  %popd
 57 :  %pprint
 58 :  %precision
 59 :  %prun
 60 :  %psearch
 61 :  %psource
 62 :  %pushd
 63 :  %pwd
 64 :  %pycat
 65 :  %pylab
 66 :  %qtconsole
 67 :  %quickref
 68 : 

In [25]:
# So, now we have learned that there are 121 magic commands and 93 of these is line magic commands and the remaining 28 
# command is cell magic commands.

In [35]:
# We can add ? to the end of a magic command to get some help about it.
# or we can use shift + tab as well
%%timeit?

----
<a href='#toc'>Back to ToC</a>

<a id='smdex'></a>
### Some Markdown Examples

#### Table of Contents

1. [Title 1](#Title-1)  

2. [Title 2](#Title-2)

1. [Title 3](#Title-3)  
    1. [Subtitle 1](#Subtitle-1)  
    1. [Subtitle 2](#Subtitle-2) 
    
1. <a href="#colnotbox">Colored Note Boxes</a>
2. <a href="#embedcode">Embedded Code Block in Markdown</a>

-----
[Back to TOC](#Table-of-Contents)

## Title 1



-----
[Back to TOC](#Table-of-Contents)

## Title 2

-----
[Back to TOC](#Table-of-Contents)

## Title 3

-----
[Back to TOC](#Table-of-Contents)

#### Subtitle-1

-----
[Back to TOC](#Table-of-Contents)

#### Subtitle-2

<a id="colnotbox"></a>
### Colored Note Boxes

<div class="alert alert-block alert-info">
    <b>Tip: ALert Block Blue</b>
</div>

<div class="alert alert-block alert-warning">
    <b>Tip: ALert Block Yellow</b>
</div>

<div class="alert alert-block alert-danger">
    <b>Tip: ALert Block Red</b>
</div>

<div class="alert alert-block alert-success">
    <b>Tip: ALert Block Green</b>
</div>

<a id="embedcode"></a>
### Embedded Code Block in Markdown

```Python
str = "This is a python block level code"
print(str)
```
```javascript
console.log("This is a javascript block level code");
```

<code>Python
str = "This is also a block level code"
print(str)
</code>

<a id='mfalt'></a>
### Math Formulae and using LaTex

In [41]:
# Some examples

alpha: $\alpha$

beta: $\beta$

 theta : $\theta$

$\int_0^{\pi} \sin(\theta)\ d\theta = 2$

The formula to calculate Body Mass Index (BMI) (assuming weight in pounds and height in inches) 

$BMI = \large{\frac{weight \times 703}{height^2}}$

$$
\Sigma=\left[
\begin{array}{ccc}
   \sigma_{11} & \cdots & \sigma_{1n} \\
   \vdots & \ddots & \vdots \\
   \sigma_{n1} & \cdots & \sigma_{nn}
\end{array}
\right]
$$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^î$

-----
[Back to TOC](#Table-of-Contents)

<a id='bif'></a>
### Built-in Functions (with embedded HTML)

In [46]:
from IPython.display import IFrame

IFrame(src='https://docs.python.org/3/library/functions.html#built-in-functions', width=1000, height=600)

----
<a href='#toc'>Back to ToC</a>

<a id='strings'></a>
### Formatted Strings

In [53]:
# Leading (prepending) zeros
num1 = 5
print(f'This is a number with leading zeros. => "{num1:07}"')

This is a number with leading zeros. => "0000005"


In [52]:
print(f'This is a number with leading spaces. => "{num1:7}"')

This is a number with leading spaces. => "      5"


In [63]:
num2 = 123.12999999
print(f'This is a number with leading zeros and three digit decimal. => "{num2:09.3f}"')

This is a number with leading zeros and three digit decimal. => "00123.130"


In [65]:
num2 = 123.12999999
print(f'This is a number with leading spaces and three digit decimal. => "{num2:9.3f}"')

This is a number with leading spaces and three digit decimal. => "  123.130"


----
<a href='#toc'>Back to ToC</a>

<a id='shadeepcopy'></a>
### Shallow and Deep Copies

In [71]:
original = ["a", "b", "c", "d"]

# deep copy 1
deep_copy1 = original[:]

# deep copy 2
deep_copy2 = original.copy()

# shallow copy
shallow_copy = original


In [72]:
# Now we will change the copies and then check if the original list has changed or not.
# First attempt
deep_copy1[:] = "dc1"

In [77]:
print("Deep Copy 1: ", deep_copy1)
print("Original:", original)

Deep Copy 1:  ['d', 'c', '1']
Original: ['a', 'b', 'c', 'd']


In [76]:
# Second attempt
deep_copy2[:] = "dc2"

In [78]:
print("Deep Copy 2: ", deep_copy2)
print("Original:", original)

Deep Copy 2:  ['d', 'c', '2']
Original: ['a', 'b', 'c', 'd']


In [80]:
# Second attempt
shallow_copy[:] = "shallow"

In [81]:
print("Shallow Copy: ", shallow_copy)
print("Original:", original)

Shallow Copy:  ['s', 'h', 'a', 'l', 'l', 'o', 'w']
Original: ['s', 'h', 'a', 'l', 'l', 'o', 'w']


In [82]:
# As we can see above, the change in a shallow copy changes the original data! 

----
<a href='#toc'>Back to ToC</a>

<a id='ladcomp'></a>
### List and Dict Comprehensions

In [97]:
# List comprehension
list_comp = [num for num in range(10)]
list_comp

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [99]:
# Dict comprehension
dict_comp = {num: {num, num**2, num**3} for num in range(3, 7)}
dict_comp

{3: {3, 9, 27}, 4: {4, 16, 64}, 5: {5, 25, 125}, 6: {6, 36, 216}}

----
<a href='#toc'>Back to ToC</a>

<a id='numpy'></a>
### Numpy

In [1]:
import numpy as np

print(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

print("np.empty: ", np.empty(10))
print("np.zeros: ", np.zeros(10))
print()
print("np.ones: ", np.ones(10))
print("np.ones_like: ", np.ones_like(np.arange(10)))
print("np.empty_like: ", np.empty_like(np.arange(10)))
print("np.zeros_like: ", np.zeros_like(np.arange(10)))

[0 1 2 3 4 5 6 7 8 9]
np.empty:  [4.67296746e-307 1.69121096e-306 1.24611673e-306 6.23058028e-307
 8.45593934e-307 7.56593017e-307 1.20161390e-306 1.78021391e-306
 1.24611470e-306 0.00000000e+000]
np.zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

np.ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
np.ones_like:  [1 1 1 1 1 1 1 1 1 1]
np.empty_like:  [0 1 2 3 4 5 6 7 8 9]
np.zeros_like:  [0 0 0 0 0 0 0 0 0 0]


In [6]:
np.empty?

In [2]:
print(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

print("np.empty: ", np.empty(10))
print("np.zeros: ", np.zeros(10))
print()
print("np.ones: ", np.ones(10))
print("np.ones_like: ", np.ones_like(np.arange(10)))
print("np.empty_like: ", np.empty_like(np.arange(10)))
print("np.zeros_like: ", np.zeros_like(np.arange(10)))

[0 1 2 3 4 5 6 7 8 9]
np.empty:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
np.zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

np.ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
np.ones_like:  [1 1 1 1 1 1 1 1 1 1]
np.empty_like:  [0 1 2 3 4 5 6 7 8 9]
np.zeros_like:  [0 0 0 0 0 0 0 0 0 0]


In [67]:
print(np.arange(7))
print(np.arange(1, 7, 2))
print(np.arange(0,6, dtype = 'float64'))
print(np.arange(0,6, dtype = 'int32'))

[0 1 2 3 4 5 6]
[1 3 5]
[0. 1. 2. 3. 4. 5.]
[0 1 2 3 4 5]


In [53]:
print(np.linspace(0,12))  # Default 50 bins
print()
print('np.linspace uses default 50 bins')
print('with the last parameter we can change the bins size.')
print(np.linspace(0, 12, 4))

[ 0.          0.24489796  0.48979592  0.73469388  0.97959184  1.2244898
  1.46938776  1.71428571  1.95918367  2.20408163  2.44897959  2.69387755
  2.93877551  3.18367347  3.42857143  3.67346939  3.91836735  4.16326531
  4.40816327  4.65306122  4.89795918  5.14285714  5.3877551   5.63265306
  5.87755102  6.12244898  6.36734694  6.6122449   6.85714286  7.10204082
  7.34693878  7.59183673  7.83673469  8.08163265  8.32653061  8.57142857
  8.81632653  9.06122449  9.30612245  9.55102041  9.79591837 10.04081633
 10.28571429 10.53061224 10.7755102  11.02040816 11.26530612 11.51020408
 11.75510204 12.        ]

np.linspace uses default 50 bins
with the last parameter we can change the bins size.
[ 0.  4.  8. 12.]


In [71]:
np.random.randint(0, 5, 3)

array([4, 1, 3])

In [75]:
a = np.arange(1, 10)

print(f"Mean value = {np.mean(a)}")
print(f"Median value = {np.median(a)}")
print(f"Variance = {np.var(a)}")
print(f"Std. Deviation = {np.std(a)}\n")

print(f"Minimum value = {np.min(a)}")
print(f"Maximum value = {np.max(a)}\n")

print(f"Sum of all values = {np.sum(a)}")
print(f"Running cumulative sum of all values = {np.cumsum(a)}\n")

print(f"Product of all values = {np.prod(a)}")
print(f"Running product of all values = {np.cumprod(a)}\n")

Mean value = 5.0
Median value = 5.0
Variance = 6.666666666666667
Std. Deviation = 2.581988897471611

Minimum value = 1
Maximum value = 9

Sum of all values = 45
Running cumulative sum of all values = [ 1  3  6 10 15 21 28 36 45]

Product of all values = 362880
Running product of all values = [     1      2      6     24    120    720   5040  40320 362880]



In [76]:
# Booleans
num_list = np.arange(7)
num_list

array([0, 1, 2, 3, 4, 5, 6])

In [108]:
print(num_list >= 2)
print(list(map(bool, num_list % 2)))
print("|= v  =|= v =|= v =|= v =|= v =|= v =|= v =|")
print(np.logical_and(num_list >= 2, num_list % 2))

[False False  True  True  True  True  True]
[False, True, False, True, False, True, False]
|= v  =|= v =|= v =|= v =|= v =|= v =|= v =|
[False False False  True False  True False]


In [109]:
#Generating fixed random values, using seed
seed = 11
RS = np.random.RandomState(seed)
RS

RandomState(MT19937) at 0x27307B88040

In [110]:
RS.randint(0, 10, 5)

array([9, 0, 1, 7, 1])

In [112]:
RS.rand(5)

array([0.10517516, 0.22571272, 0.89634075, 0.82618135, 0.09281249])

In [113]:
RS.randn(5)

array([0.32997265, 0.6015713 , 1.49211767, 0.09358016, 1.55013341])

----
<a href='#toc'>Back to ToC</a>

<a id='arraydtypes'></a>
### Array Data Types

In [63]:
# Array Data Types
for key, val in np.sctypeDict.items():
    print(f'{str(key).ljust(12)} : {val}')

?            : <class 'numpy.bool_'>
0            : <class 'numpy.bool_'>
byte         : <class 'numpy.int8'>
b            : <class 'numpy.int8'>
1            : <class 'numpy.int8'>
ubyte        : <class 'numpy.uint8'>
B            : <class 'numpy.uint8'>
2            : <class 'numpy.uint8'>
short        : <class 'numpy.int16'>
h            : <class 'numpy.int16'>
3            : <class 'numpy.int16'>
ushort       : <class 'numpy.uint16'>
H            : <class 'numpy.uint16'>
4            : <class 'numpy.uint16'>
i            : <class 'numpy.intc'>
5            : <class 'numpy.intc'>
uint         : <class 'numpy.uint32'>
I            : <class 'numpy.uintc'>
6            : <class 'numpy.uintc'>
intp         : <class 'numpy.int64'>
p            : <class 'numpy.int64'>
9            : <class 'numpy.int64'>
uintp        : <class 'numpy.uint64'>
P            : <class 'numpy.uint64'>
10           : <class 'numpy.uint64'>
long         : <class 'numpy.int32'>
l            : <class 'numpy.int32'>

----
<a href='#toc'>Back to ToC</a>

<a id='pandas'></a>
### Pandas

In [115]:
import pandas as pd
pd.Series(range(5), index=['a', 'b', 'c', 'd', 'e'])

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [121]:
# DataFrame from dictionary
a_dict = {'A' : [0, 1, 2, 3, np.NaN],
          'B' : ['a', 'b', 'c', 'd', 'e'],
          'C' : [1.0, None, 1.2, 1.3, 1.4],
          'D' : [np.nan, np.nan, np.nan, np.nan, np.nan],
          'E' : [['a', 7], None, 77 , 'this column is object type', 0.99]
         }

# Create DataFrame
df = pd.DataFrame(a_dict)
df

A  B    C   D                           E
0  0.0  a  1.0 NaN                      [a, 7]
1  1.0  b  NaN NaN                        None
2  2.0  c  1.2 NaN                          77
3  3.0  d  1.3 NaN  this column is object type
4  NaN  e  1.4 NaN                        0.99

In [120]:
# !! Carefully check the 'None' values in columns C and E.
# They are converted differently. 
# This is because of the dtypes of the columns.

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       4 non-null      float64
 1   B       5 non-null      object 
 2   C       4 non-null      float64
 3   D       0 non-null      float64
 4   E       4 non-null      object 
dtypes: float64(3), object(2)
memory usage: 328.0+ bytes


In [122]:
df.sample(3)

A  B    C   D       E
4  NaN  e  1.4 NaN    0.99
2  2.0  c  1.2 NaN      77
0  0.0  a  1.0 NaN  [a, 7]

In [123]:
df.C.nlargest()

4    1.4
3    1.3
2    1.2
0    1.0
Name: C, dtype: float64

In [124]:
df.C.nsmallest(2)

0    1.0
2    1.2
Name: C, dtype: float64

In [127]:
df.C.cumsum()

0    1.0
1    NaN
2    2.2
3    3.5
4    4.9
Name: C, dtype: float64

In [128]:
df.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [129]:
df.loc[[0, 3], ['B', 'D']]

B   D
0  a NaN
3  d NaN

In [130]:
df.iloc[2:5, 1:4]

B    C   D
2  c  1.2 NaN
3  d  1.3 NaN
4  e  1.4 NaN

In [131]:
# Drop all rows with missing values
df2 = df.dropna()
df2

Empty DataFrame
Columns: [A, B, C, D, E]
Index: []

In [132]:
# Drop all rows with missing values
df2 = df.dropna(axis=1)
df2

B
0  a
1  b
2  c
3  d
4  e

In [135]:
# Fill missing values with a constant value of zero
df4 = df.fillna(999)
df4

A  B      C      D                           E
0    0.0  a    1.0  999.0                      [a, 7]
1    1.0  b  999.0  999.0                         999
2    2.0  c    1.2  999.0                          77
3    3.0  d    1.3  999.0  this column is object type
4  999.0  e    1.4  999.0                        0.99

In [136]:
# Fill missing values with the mean value for the respective column
df5 = df.fillna(df.mean())
df5

A  B      C   D                           E
0  0.0  a  1.000 NaN                      [a, 7]
1  1.0  b  1.225 NaN                        None
2  2.0  c  1.200 NaN                          77
3  3.0  d  1.300 NaN  this column is object type
4  1.5  e  1.400 NaN                        0.99

In [138]:
# transposing the DataFrame
df.T

0     1    2                           3     4
A       0     1    2                           3   NaN
B       a     b    c                           d     e
C       1   NaN  1.2                         1.3   1.4
D     NaN   NaN  NaN                         NaN   NaN
E  [a, 7]  None   77  this column is object type  0.99

----
<a href='#toc'>Back to ToC</a>

<a id='readwrite'></a>
### Reading / Writing Files

#### Info about Pickle

Saving and reading data
while reading or writing to a csv or an excel file, data types are not preserved.
If we want to preserve the data types, we can use pickle for saving or reading files!

In [150]:
# writing to a file
temp_file = 'temp.txt'

with open(temp_file, 'w') as to_write:
    to_write.write('First Line.\n')
    to_write.write('Second Line.')

In [153]:
# reading a file
with open(temp_file, 'r') as file:
    for line in file:
        print(line, end="")

First Line.
Second Line.

In [146]:
# reading a file
with open(temp_file, 'r') as file:
    lines = file.readlines()
    print(lines)

['First Line.\n', 'Second Line.']


In [154]:
df

A  B    C   D                           E
0  0.0  a  1.0 NaN                      [a, 7]
1  1.0  b  NaN NaN                        None
2  2.0  c  1.2 NaN                          77
3  3.0  d  1.3 NaN  this column is object type
4  NaN  e  1.4 NaN                        0.99

In [155]:
import pickle

pk = 'test.pk'

with open(pk, 'wb') as pickle_write:
    pickle.dump(df, pickle_write)

In [157]:
with open(pk, 'rb') as read_pickle:
    df_pk = pickle.load(read_pickle)

df_pk

A  B    C   D                           E
0  0.0  a  1.0 NaN                      [a, 7]
1  1.0  b  NaN NaN                        None
2  2.0  c  1.2 NaN                          77
3  3.0  d  1.3 NaN  this column is object type
4  NaN  e  1.4 NaN                        0.99

In [158]:
df.to_pickle('test2.pk')

df_pk2 = pd.read_pickle('test2.pk')
df_pk2

A  B    C   D                           E
0  0.0  a  1.0 NaN                      [a, 7]
1  1.0  b  NaN NaN                        None
2  2.0  c  1.2 NaN                          77
3  3.0  d  1.3 NaN  this column is object type
4  NaN  e  1.4 NaN                        0.99

----
<a href='#toc'>Back to ToC</a>